### ISSUE TITLE
求论文正文

### ISSUE THREAD

**Issue by WasFun00** [wty-yy/KataCR#1]
作者你好，我最近也开始准备毕设，对你强化学习的具体实现方式很感兴趣，不知能否拜读一下此项目最终形成的论文？

**Comment by wty-yy** [comment]
论文latex源代码：https://github.com/wty-yy/LaTex-Projects/tree/main/undergraduate_program
这里面的pdf就是论文最终版


在博客也有论文：https://wty-yy.xyz/posts/12073/



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月27日(周二) 晚上7:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wty-yy/KataCR] 求论文正文 (Issue #1)




 
作者你好，我最近也开始准备毕设，对你强化学习的具体实现方式很感兴趣，不知能否拜读一下此项目最终形成的论文？

**Comment by WasFun00** [comment]
感谢
