### ISSUE TITLE
Linux VM

### ISSUE THREAD

**Issue by LytexWZ** [wty-yy/KataCR#2]
Can we start this project and use it in a VMware linux dist?

**Comment by wty-yy** [comment]
This should be possible, but you need to consider whether Ubuntu in the VM can connect to the Android phone through Scrcpy, so some serial port configuration is required, whether cuda can be used, etc. (the model inference speed in the VM may not be as fast as local deployment)



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 11, 2024 04:48 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [wty-yy/KataCR] Linux VM (Issue #2)




 
Can we start this project and use it in a VMware linux dist?

**Comment by LytexWZ** [comment]
Hmmm then I will create a partition on my C:\\ and install Ubuntu. thanks for the fast response
